### ISSUE TITLE
resolveHtml: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Domitnator** [Kentico/kontent-delivery-sdk-js#269]
### Brief bug description

When we try to use 2 typeresolvers, which use the richTextResolver-callback, we get an error :

```
 ERROR  Cannot read property 'length' of undefined                                                                                                                                                  10:00:41  

  at Preprocessor.write (node_modules\@kentico\kontent-delivery\node_modules\parse5\lib\tokenizer\preprocessor.js:86:38)
  at Tokenizer.write (node_modules\@kentico\kontent-delivery\node_modules\parse5\lib\tokenizer\index.js:265:27)
  at Parser.parseFragment (node_modules\@kentico\kontent-delivery\node_modules\parse5\lib\parser\index.js:371:24)
  at Object.parseFragment (node_modules\@kentico\kontent-delivery\node_modules\parse5\lib\index.js:22:19)
  at Parse5RichTextParser.resolveRichTextElement (node_modules\@kentico\kontent-delivery\_commonjs\parser\adapters\parse5-rich-text.parser.js:13:41)
  at Parse5RichTextParser.processModularContentItem (node_modules\@kentico\kontent-delivery\_commonjs\parser\adapters\parse5-rich-text.parser.js:164:39)
  at node_modules\@kentico\kontent-delivery\_commonjs\parser\adapters\parse5-rich-text.parser.js:36:27
  at Array.forEach (<anonymous>)
  at Parse5RichTextParser.processRichTextElement (node_modules\@kentico\kontent-delivery\_commonjs\parser\adapters\parse5-rich-text.parser.js:34:22)
  at Parse5RichTextParser.resolveRichTextElement (node_modules\@kentico\kontent-delivery\_commonjs\parser\adapters\parse5-rich-text.parser.js:15:27)
  at RichTextResolver.resolveData (node_modules\@kentico\kontent-delivery\_commonjs\resolvers\rich-text.resolver.js:20:46)
  at RichTextElement.resolveRichTextFunc (node_modules\@kentico\kontent-delivery\_commonjs\mappers\element.mapper.js:169:53)
  at RichTextElement.resolveHtml (node_modules\@kentico\kontent-delivery\_commonjs\elements\elements.js:156:38)
  at context.app.$deliveryClient.viaCache.then.res (index.vue:98:0)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Repro steps

In our kentico.ai we have a richttext field which has a linked-item:

![image](https://user-images.githubusercontent.com/13468638/69792838-a4d7ed80-11c7-11ea-992b-9792f9d18087.png)

In our nuxtjs configuration we have 2 ContentItem types:

```
import { ContentItem } from '@kentico/kontent-delivery';
import { resolveContentLink } from '../kenticokontent/ContentLinks';

export default class Pagina extends ContentItem {
    constructor() {
        super({
            richTextResolver: (item, context) => {
                console.log('richTextResolver fired for Pagina....');
            },
            urlSlugResolver: (link, context) => resolveContentLink(link, context)
        });
    }
}
```

and 

```
import { ContentItem } from '@kentico/kontent-delivery';
import { resolveContentLink } from '../kenticokontent/ContentLinks';

export default class Downloads extends ContentItem {
    constructor() {
        super({
            richTextResolver: (item, context) => {
                console.log('richTextResolver fired for downloads....');          
            },
            urlSlugResolver: (link, context) => resolveContentLink(link, context)
        });
    }
}
```

and when we register them both:

```
$deliveryClient.config.typeResolvers = [
        new TypeResolver('pagina', () => new Pagina()),
        new TypeResolver('downloads', () => new Downloads())
    ]
```

we get the error "Cannot read property 'length' of undefined".

To "solve" this issue i can do 2 things:

1. Register only 1 typeresolver
2. Have them both registered but remove the richTextResolver-callback in both types (pagina and downloads)

So it looks like there is an issue when multiple typeresolvers register the richTextResolver-callback.

### Expected behavior

Use multiple typeresolvers with the richTextResolver-callback without issues.

### Test environment

 - Node and Javascript
 - NuxtJS
 - @kentico/kontent-delivery: "8.1.0"

**Comment by Enngage** [comment]
Hey, 

We are using multiple `TypeResolvers` in many projects so thats definitely not a problem. From the stractrace I can see that the code is running on node.js and that the exception is coming from the `parse5` library - probably due to invalid / missing html. 

This could make sense as it your example your are `not` returning any value from `richTextResolver`. Depending on what IDE you are using you should be notified that you cannot use `richTextResolver` without a return value. 

Try replacing:

```
richTextResolver: (item, context) => {
      console.log('richTextResolver fired for downloads....');          
},
```

with 

```
richTextResolver: (item, context) => {
  return 'testItem';     
},
```

**Comment by Domitnator** [comment]
That's it indeed! Thanks for your quick response!
