### ISSUE TITLE
Links and images not resolving correctly when included in an inline component

### ISSUE THREAD

**Issue by benmorana** [Kentico/kontent-delivery-sdk-js#294]
### Brief bug description

Most of our URL resolving uses the context.item variable in the urlSlugResolver function. When context.item is not available, we instead instruct the resolver to return a blank URL. We've had no issues resolving images or content item links included directly in a rich text field. However, when we include either of those in the rich text field of an inline component inside another rich-text field, context.item is no longer available or we get an error saying that the image data is not available.

### Repro steps

1. Go to Kentico Kontent
2. Create a component that will be used as an inline component only ( say blockquote) and include a rich text field as part of its content model. 
3. Include the component as an inline component in another content item's rich text ( do not convert as content item) and include either a hyperlinked text linking to another content item (which uses a URL slug resolver and context.item to create the link - similar to the below), or an image asset in the rich text field we created in Step 2. 
```
      urlSlugResolver: (link, context) => {
        if (!context.item) {
          throw new Error('context.item is not available');
        }
        if (context.item.microsite.value.length === 1) {
          return { url: `/${context.item.microsite.value.reduce((acc, elem) => elem.codename, '')}` };
        }
        return { url: '' };
      },
```
4. Try to resolve the inline component using the Kentico Kontent JS SDK and notice that either context.item is not available, or you get something akin to this error when trying to resolve the image:

```
(node:5266) UnhandledPromiseRejectionWarning: Error: Image with id '34073adc-54b8-4b3e-bf64-1949f57aa4a4' was not found in images data for linked item 'how_we_help_e3eee59' and element 'body'
    at RichTextResolver.getImageResult (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/resolvers/rich-text.resolver.js:92:19)
    at Object.getImageResult (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/resolvers/rich-text.resolver.js:40:30)
    at Parse5RichTextParser.processImage (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:66:38)
    at /Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:37:27
    at Array.forEach (<anonymous>)
    at Parse5RichTextParser.processRichTextElement (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:34:22)
    at /Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:42:27
    at Array.forEach (<anonymous>)
    at Parse5RichTextParser.processRichTextElement (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:34:22)
    at /Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:42:27
    at Array.forEach (<anonymous>)
    at Parse5RichTextParser.processRichTextElement (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:34:22)
    at Parse5RichTextParser.resolveRichTextElement (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:15:27)
    at RichTextResolver.resolveData (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/resolvers/rich-text.resolver.js:20:46)
    at RichTextElement.resolveRichTextFunc (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/mappers/element.mapper.js:163:53)
    at RichTextElement.resolveHtml (/Users/benoitmorana/Documents/development/project-mesh/node_modules/@kentico/kontent-delivery/_commonjs/elements/elements.js:157:38)
(node:5266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

### Expected behavior

Context.item (inside the urlSlugResolver funciton)  or image data is available even when nested inside an inline component, and allows URLs dependant on context.item to resolve fully.

### Test environment

 - Node v14.2.0
 - Kentico Kontent SDK v9.1.1

**Comment by Enngage** [comment]
Hi @benmorana,

Thank you for detailed explanation! I'll have a look at this issue and try to reproduce it in upcoming week.

**Comment by Enngage** [comment]
@benmorana Can you please provide me with some response json input I can try on my end? I haven't been able to reproduce this on my end sadly.

**Comment by benmorana** [comment]
@Enngage - Thanks for taking a quick look. I think I might have figured out why some of the links weren't resolving correctly, but the issue still remains with the image not resolving inside an inline component that is nested inside an existing rich text field. 

I've just added you as a collaborator on a repo that has some dummy data in `input.json` and also an example configuration with the models/resolvers. If you'd like to replicate this with your own Kentico Kontent set up, here's a screenshot of what it looks like in the system:

![image](https://user-images.githubusercontent.com/37203622/88606048-fd48ed00-d0be-11ea-92e8-09f4241a8fb9.png)

On my end if I try to run `npm run test`, I still get the following error:

```
(node:4972) UnhandledPromiseRejectionWarning: Error: Image with id '0f15797d-5d61-4240-b112-1a11e5321d38' was not found in images data for linked item 'test_page_with_inline_component' and element 'body'
    at RichTextResolver.getImageResult (/Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/resolvers/rich-text.resolver.js:92:19)
    at Object.getImageResult (/Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/resolvers/rich-text.resolver.js:40:30)
    at Parse5RichTextParser.processImage (/Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:65:38)
    at /Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:36:27
    at Array.forEach (<anonymous>)
    at Parse5RichTextParser.processRichTextElement (/Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:33:22)
    at /Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:41:27
    at Array.forEach (<anonymous>)
    at Parse5RichTextParser.processRichTextElement (/Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:33:22)
    at /Users/benoitmorana/Documents/development/test-kentico-resolvers/node_modules/@kentico/kontent-delivery/_commonjs/parser/adapters/parse5-rich-text.parser.js:41:27
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Enngage** [comment]
Hey @benmorana,

Thank you for sending the repo. I found few issues within your code which I would like to clarify:

- You are attempting to `resolveHtml` method on data which you get by parsing json which you previously saved, but this will not work because the `resolveHtml` is a method on `RichTextTextElement` and if you only parse some json, that method is not there. Therefore I'm not able to reproduce the issue locally in your repo. You should use `MappingService` in combination with raw response (in input.json you are storing response processed by SDK, but you need to use raw response you get from API - raw response is available in SDK response in debug property). I've modified the code a bit and pushed it to another branch, can you take a look?

- The error you sent is trying to get an image with id `0f15797d-5d61-4240-b112-1a11e5321d38`, but such id is not present in the sample `input.json` you provided. In the code I see you are using `itemsFeedAll` endpoint which means that **every single item** in your project is being fetched. This leads me to believe that the image could be deleted, but there still is some published content item that references this image.

**Comment by benmorana** [comment]
Hi @Enngage - Look like trying to generate and output the data as JSON is causing issues. In that case, it might just be easiest for me to give you access to the sample project I created for this example. I've added your email address that's referenced in your Github profile to the project, but let me know if there's another/better email address I should be adding. 

In response to your other question about the image having potentially been deleted, you should see that in the project I sent through there's only two content items and one asset. I only added those items and nothing else was added or deleted, so it doesn't feel like the issue is coming from the itemsFeedAll method fetching an outdated item. But please let me know if I'm not understanding something :) 

PS I've also updated the test repo so that now it's only fetching from the API rather than from the `input.json` file. You might just need to update the .env file with the Project ID.

**Comment by Enngage** [comment]
Thank you for that ;) I've been able to reproduce your issue and there is something I missed previously - in `inline_component.js` you are calling `resolveHtml` inside `richTextResolver` which is what is causing this behavior. Well, even if you didn't call `resolveHtml` it would still fail if you tried to use the `value` property of rich text element. Strangely, this has been the case only for parsing html using `parse5`, browser parsing worked well.

I've improved image handling in general for parsing and it should now cover more scenarios. Can you update to `9.2.0` and see if it helps?

**Comment by benmorana** [comment]
@Enngage Fantastic! I can now see the nested image and links resolving correctly. Thanks for getting that fixed so quickly 👍
